defaults:
  run:
    shell: bash
env:
  GONOPROXY: github.com/getsynq/*
  GONOSUMDB: github.com/getsynq/*
  GOPRIVATE: github.com/getsynq/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-synq-dbt-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        restore-keys: |
          ${{ runner.os }}-synq-dbt-
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - name: Install Protoc
      uses: arduino/setup-protoc@v1.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: 3.9.1
    - name: Install protoc generators
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.0.1
        go install github.com/nefixestrada/protoc-gen-go-grpc-mock@latest
    - name: Configure ssh agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Configure git
      run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - name: Build dev-tools
      run: go build -o ../bin/dev-tools main.go
      working-directory: dev-tools
    - name: Build
      run: |
        go generate
        go get
        GOOS=darwin GOARCH=arm64 go build -o synq-dbt-arm64-darwin main.go
        GOOS=linux GOARCH=amd64 go build -o synq-dbt-amd64-linux main.go
        GOOS=windows GOARCH=amd64 go build -o synq-dbt-amd64-windows.exe main.go
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
         synq-dbt-arm64-darwin
         synq-dbt-amd64-linux
         synq-dbt-amd64-windows.exe
name: release synq-dbt
"on":
  push:
    tags:
      - synq-dbt-v*.*.*
